# 🐳 Docker 개념 간단 정리

## Docker란?
> 애플리케이션을 **컨테이너**라는 격리된 환경에 패키징해서 어디서든 동일하게 실행할 수 있게 해주는 플랫폼

"내 컴퓨터에서는 되는데..." 문제를 해결해 준다.

---

## 핵심 개념

### 📦 Image (이미지)
- 컨테이너를 만들기 위한 **읽기 전용 템플릿**
- 레이어(layer) 구조로 구성
- 예: `ubuntu:22.04`, `node:18`, `python:3.11`

### 🏃 Container (컨테이너)
- 이미지를 실행한 **인스턴스**
- 격리된 프로세스 환경
- 이미지 1개 → 컨테이너 N개 생성 가능

### 📄 Dockerfile
- 이미지를 만들기 위한 **설계도 (스크립트)**
- 어떤 OS, 어떤 패키지, 어떤 명령을 실행할지 정의

```dockerfile
FROM node:18
WORKDIR /app
COPY . .
RUN npm install
CMD ["node", "index.js"]
```

### 🗂️ Docker Hub
- 이미지를 저장하고 공유하는 **원격 저장소**
- GitHub의 이미지 버전이라고 보면 됨
- [hub.docker.com](https://hub.docker.com)

### + "이미지"라고 부르는 이유
 - 이미지는 실행 전 상태이기 때문.
 - 이미지 = 설치된 OS, 파일, 설정이 담긴 스냅샷 (정지된 상태)
 - 컨테이너 = 이미지를 실행한 상태

     - 이 둘을 구분하는 게 Docker의 핵심 개념.

<b>비유하면:

![image.png](attachment:1dc9c0dc-d3c7-4ee1-8fd5-db4935d53898.png)


틀(이미지) 하나로 붕어빵(컨테이너)을 100개 찍어낼 수 있다.



### 🔗 Docker Compose
- **여러 컨테이너**를 한 번에 정의하고 실행
- `docker-compose.yml` 파일로 관리
- 예: 앱 서버 + DB + Redis를 함께 구동

```yaml
services:
  app:
    build: .
    ports:
      - "3000:3000"
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: secret
```

---

## VM vs Docker

| 항목 | VM (가상머신) | Docker (컨테이너) |
|------|-------------|-----------------|
| 크기 | GB 단위 | MB 단위 |
| 시작 속도 | 분 단위 | 초 단위 |
| OS | 각각 독립 OS | 호스트 OS 공유 |
| 격리 수준 | 완전 격리 | 프로세스 격리 |
| 성능 | 상대적으로 낮음 | 거의 네이티브 수준 |

---

## 자주 쓰는 명령어

```bash
# 이미지 다운로드
docker pull nginx

# 컨테이너 실행
docker run -d -p 8080:80 nginx

# 실행 중인 컨테이너 목록
docker ps

# 컨테이너 중지 / 삭제
docker stop <id>
docker rm <id>

# 이미지 목록 / 삭제
docker images
docker rmi <image>

# 이미지 빌드
docker build -t my-app .

# 컨테이너 내부 접속
docker exec -it <id> bash

# Compose 실행 / 종료
docker compose up -d
docker compose down
```

---

## 동작 흐름 요약

```
Dockerfile
    ↓  docker build
  Image
    ↓  docker run
Container (실행 중인 앱)
```

---

## 언제 쓰면 좋은가?

- ✅ 개발 환경을 팀원과 **동일하게** 맞추고 싶을 때
- ✅ 서버 배포를 **빠르고 일관되게** 하고 싶을 때
- ✅ 여러 서비스(앱, DB, 캐시 등)를 **함께 구동**할 때
- ✅ CI/CD 파이프라인에서 **테스트 환경**을 격리할 때


# <font size=6><b>Lec01.LLM_전처리
* https://wikidocs.net/book/2155

In [1]:
#! pip install nltk
#! pip install konlpy, mecab, jpype(whl)

<pre>
텍스트 전처리(Text preprocessing) - 9가지 
언어 모델(Language Model) - 영어 / 한국어전용(KoBERT)

카운트 기반의 단어 표현(Count based word Representation) -  DTM(Document Term Matrix)
                                                          TF-IDF(Term Frequency-Inverse Document Frequency)
벡터의 유사도(Vector Similarity)  - [실습]감성분석, 유사도분석

워드 임베딩(Word Embedding) - 텍스트를 적절히 숫자 , ~~억대 피쳐(압축)

RNN을 이용한 텍스트 분류(Text Classification)  - [실습]영화리뷰, 감성분석

--------------------------------------------------------  가상화 , 컨네이너 
Docker - 병렬, 실시간(스트림)

--------------------------------------------------------  심화 (LLM언어모델)
인코딩/디코딩
어텐션            +  GPT
트랜스포어 

--------------------------------------------------------  서비스 
LAG
Lang Chain
Agent 단일
Agent 멀티

펄플렉서티(Perplexity, PPL): 언어 모델 성능지표

# <b>[1]토큰화(Tokenization)
* 주어진 코퍼스(corpus)에서 토큰(token)이라 불리는 단위로 나누는 작업
* 토큰 : 문장, 단어, 형태소, 품사
* NLTK, KoNLPY

## <b>nltk

### 단어 자르기

In [2]:
from nltk.tokenize import word_tokenize
from nltk.tokenize import WordPunctTokenizer
from nltk.tag import pos_tag

In [3]:
import nltk
nltk.download('punkt_tab')    #C:\Users\user\AppData\Roaming\nltk_data\tokenizers\english\

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\PC\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [4]:
sentense = "Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop."
print('단어 토큰화1 :',word_tokenize(sentense))
print('단어 토큰화2 :',WordPunctTokenizer().tokenize(sentense))

단어 토큰화1 : ['Do', "n't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr.', 'Jone', "'s", 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop', '.']
단어 토큰화2 : ['Don', "'", 't', 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr', '.', 'Jone', "'", 's', 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop', '.']


### 품사 태깅

In [5]:
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\PC\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger_eng.zip.


True

In [6]:
sentense = "I am actively looking for Ph.D. students. and you are a Ph.D. student."
print('단어 토큰화1 :',word_tokenize(sentense))
print('품사 태깅 :',pos_tag(word_tokenize(sentense)))

단어 토큰화1 : ['I', 'am', 'actively', 'looking', 'for', 'Ph.D.', 'students', '.', 'and', 'you', 'are', 'a', 'Ph.D.', 'student', '.']
품사 태깅 : [('I', 'PRP'), ('am', 'VBP'), ('actively', 'RB'), ('looking', 'VBG'), ('for', 'IN'), ('Ph.D.', 'NNP'), ('students', 'NNS'), ('.', '.'), ('and', 'CC'), ('you', 'PRP'), ('are', 'VBP'), ('a', 'DT'), ('Ph.D.', 'NNP'), ('student', 'NN'), ('.', '.')]


### 문장 자르기

In [7]:
from nltk.tokenize import sent_tokenize

text = """192.168.38.1 His barber kept his word. 
But Dr.kim keeping such a huge secret to himself was driving him crazy. 
Finally, the barber went up a mountain and almost to the edge of a cliff. 
He dug a hole in the midst of some reeds. 
He looked about, to make sure no one was near."""

print('문장 토큰화1 :',  len(sent_tokenize(text))  , sent_tokenize(text) )

문장 토큰화1 : 5 ['192.168.38.1 His barber kept his word.', 'But Dr.kim keeping such a huge secret to himself was driving him crazy.', 'Finally, the barber went up a mountain and almost to the edge of a cliff.', 'He dug a hole in the midst of some reeds.', 'He looked about, to make sure no one was near.']


## <b>keras

### 단어 자르기

#### <font color=red size=5><b>단일문장 : text_to_word_sequence ★★★

In [8]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence
sentense = "Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop."
print('단어 토큰화3 :',text_to_word_sequence(sentense))

단어 토큰화3 : ["don't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', 'mr', "jone's", 'orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop']


### 문장 자르기

#### <font color=red size=5><b>여러문장 : Tokenizer ★★★★★★★★★★

In [41]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

text = ["나는 오늘 친구랑 학교에 간다." 
        ,"너는 오늘 집에 간다"]

tk = Tokenizer()
tk.fit_on_texts(text)                                #-------------------[1]문장/단어자르기
#문장 자르면 단어사전구축가능
print(tk.word_index)                                 #-----------사전확인 : 단어 인덱스
print(tk.word_counts)                                 #-----------사전확인 : 단어 빈도

res = tk.texts_to_sequences(text)                    #-------------------[2]임베딩(단어자르기->인코딩->리스트)
print(res)                                           #-----------임베딩(인코딩된단어집합)확인 


pad = pad_sequences(res, maxlen=5,  padding='post')  #--------------------[3]패딩
print(pad)

{'오늘': 1, '간다': 2, '나는': 3, '친구랑': 4, '학교에': 5, '너는': 6, '집에': 7}
OrderedDict([('나는', 1), ('오늘', 2), ('친구랑', 1), ('학교에', 1), ('간다', 2), ('너는', 1), ('집에', 1)])
[[3, 1, 4, 5, 2], [6, 1, 7, 2]]
[[3 1 4 5 2]
 [6 1 7 2 0]]


* <font color=blue><b>TextVectorization

In [10]:
from tensorflow.keras.layers import TextVectorization

text = ["나는 오늘 친구랑 학교에 간다." 
        ,"너는 오늘 집에 간다"]

vec = TextVectorization(output_mode="int" , output_sequence_length=5)
vec.adapt(text)                        #------------------ fit :: [1][2][3]문장자르기,단어자르기,패딩

res = vec(text)                        #------------------ transform :: 
print(res)

vocab = vec.get_vocabulary()           #-----------사전확인
#print(vocab)
word_index = {word: idx for idx, word in enumerate(vocab)}
print(word_index)

tf.Tensor(
[[8 2 5 4 3]
 [7 2 6 3 0]], shape=(2, 5), dtype=int64)
{'': 0, '[UNK]': 1, '오늘': 2, '간다': 3, '학교에': 4, '친구랑': 5, '집에': 6, '너는': 7, '나는': 8}


## <b>konlpy
* KoNLPy(코엔엘파이) 패키지
    * Okt(Open Korea Text), 코모란(Komoran), 한나눔(Hannanum), 꼬꼬마(Kkma)
    * <font color=red><b>메캅(Mecab)</b>

### 단어 자르기

In [11]:
from konlpy.tag import Okt
from konlpy.tag import Kkma
from konlpy.tag import Komoran

okt = Okt()
kkma = Kkma()
komoran= Komoran()

print(komoran.morphs("아버지가방에들어가신다"))
print(komoran.pos("아버지가방에들어가신다"))
print(komoran.nouns("아버지가방에들어가신다"))

print('OKT 형태소 분석 :',okt.morphs("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))
print('OKT 품사 태깅 :'  ,okt.pos   ("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))
print('OKT 명사 추출 :'  ,okt.nouns ("열심히 코딩한 당신, 연휴에는 여행을 가봐요")) 

['아버지', '가방', '에', '들어가', '시', 'ㄴ다']
[('아버지', 'NNG'), ('가방', 'NNP'), ('에', 'JKB'), ('들어가', 'VV'), ('시', 'EP'), ('ㄴ다', 'EC')]
['아버지', '가방']
OKT 형태소 분석 : ['열심히', '코딩', '한', '당신', ',', '연휴', '에는', '여행', '을', '가봐요']
OKT 품사 태깅 : [('열심히', 'Adverb'), ('코딩', 'Noun'), ('한', 'Josa'), ('당신', 'Noun'), (',', 'Punctuation'), ('연휴', 'Noun'), ('에는', 'Josa'), ('여행', 'Noun'), ('을', 'Josa'), ('가봐요', 'Verb')]
OKT 명사 추출 : ['코딩', '당신', '연휴', '여행']


In [12]:
from konlpy.tag import Mecab
mecab = Mecab(dicpath=r"C:/mecab/mecab-ko-dic")  #------- 역슬러시 인식 불가 , 슬러시 사용

print('Mecab 형태소 분석 :', mecab.morphs("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))
print('Mecab 품사 태깅 :'  , mecab.pos   ("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))
print('Mecab 명사 추출 :'  , mecab.nouns ("열심히 코딩한 당신, 연휴에는 여행을 가봐요")) 

Mecab 형태소 분석 : ['열심히', '코딩', '한', '당신', ',', '연휴', '에', '는', '여행', '을', '가', '봐요']
Mecab 품사 태깅 : [('열심히', 'MAG'), ('코딩', 'NNG'), ('한', 'XSA+ETM'), ('당신', 'NP'), (',', 'SC'), ('연휴', 'NNG'), ('에', 'JKB'), ('는', 'JX'), ('여행', 'NNG'), ('을', 'JKO'), ('가', 'VV'), ('봐요', 'EC+VX+EC')]
Mecab 명사 추출 : ['코딩', '당신', '연휴', '여행']


* <font color=red><b>한국어엔 부적합

In [13]:
sentense = "열심히 코딩한 당신, 연휴에는 여행을 가봐요"
print('단어 토큰화3 :',text_to_word_sequence(sentense))

단어 토큰화3 : ['열심히', '코딩한', '당신', '연휴에는', '여행을', '가봐요']


# <b>[2]  어간 추출(stemming) , 표제어 추출(lemmatizaiton)

* 정제(cleaning)
    - 특수기호 , <font color=red><b>불용어</b></font> (a is the 이 그 저 이다....) -> 노이즈 제거<br><br>
* 정규화(normalization) 
    - 표현이 다른 단어들을 한 단어로 표현 (빨갛고 붉게 붉은 --> 빨갛다)
    - <font color=red><b>어간(Stemming), 표제어(Lemmatization) 추출</b></font> --->  단어수 줄이기

| 구분 | 어간 추출 (Stemming) | 표제어 추출 (Lemmatization) |
| :--- | :--- | :--- |
| **핵심 개념** | 정해진 규칙에 따라 단어 뒷부분을 자름 | 단어의 형태학적 분석을 통해 원형을 찾음 |
| **특징** | 속도가 매우 빠름 (단순 컷팅) | 속도가 상대적으로 느림 (문맥 고려) |
| **결과물** | 사전에 없는 단어일 수 있음 (예: `formali`) | 항상 사전에 있는 표준 단어 (예: `formal`) |
| **정확도** | 낮음 (대충 자름) | 높음 (사전적 의미 유지) |
| **도구** | `PorterStemmer`, `LancasterStemmer` | `WordNetLemmatizer` |

## <b>nltk

### 어간 추출(stemming)
* formalize → formal
* allowance → allow
* electricical → electric

In [20]:
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize

stemmer = PorterStemmer()

tokenized_sentence = word_tokenize('Bones')
print('어간 추출 전 :', tokenized_sentence)
print('어간 추출 후 :',stemmer.stem('Bones'))

어간 추출 전 : ['Bones']
어간 추출 후 : bone


### 표제어 추출
* 어간 + 접사 : 사전적 의미 추철
    * am, are, is  -> be
    * cats -> cat

In [15]:
import nltk
nltk.download('wordnet')    #C:\Users\user\AppData\Roaming\nltk_data\tokenizers\english\

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\PC\AppData\Roaming\nltk_data...


True

In [16]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()
lemmatizer.lemmatize('watched', 'v')

'watch'

# <b>[3]  불용어(Stopword)

* 정제(cleaning)
    - 특수기호 , <font color=red><b>불용어</b></font> (a is the 이 그 저 이다....) -> 노이즈 제거<br>

## <b>nltk
* C:\Users\PC\AppData\Roaming\nltk_data\corpora\stopwords -> 경로

### 불용어 사전 로드

In [23]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\PC\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [21]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize 

In [29]:
stop_words_list = stopwords.words('english')
print('불용어 개수 :', len(stop_words_list))
print('불용어 10개 출력 :',stop_words_list[:10])


불용어 개수 : 198
불용어 10개 출력 : ['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an']


In [28]:
stop_words_list = stopwords.words('my_korean')
print('불용어 개수 :', len(stop_words_list))
print('불용어 10개 출력 :',stop_words_list[:10])


불용어 개수 : 595
불용어 10개 출력 : ['가', '가까스로', '가령', '각', '각각', '각자', '각종', '갖고말하자면', '같다', '같이']


### 문장 내 불용어 제거

In [30]:
example = "Family is not an important thing. It's everything."
stop_words = set(stopwords.words('english')) 

word_list = word_tokenize(example)

result = []
for word in word_list: 
    if word not in stop_words: 
        result.append(word) 

print('불용어 제거 전 :',word_list) 
print('불용어 제거 후 :',result)


불용어 제거 전 : ['Family', 'is', 'not', 'an', 'important', 'thing', '.', 'It', "'s", 'everything', '.']
불용어 제거 후 : ['Family', 'important', 'thing', '.', 'It', "'s", 'everything', '.']


## <b>konlpy

In [ ]:
from konlpy.tag import Okt

# <b>[4] 임베딩
* 문장 내 단어 인코딩 집합
* ["너는 오늘 집에 간다"] -->[6,1,7,2]
* <b>OOV(out of vaca): 사전에 없는 단어</b>
    * keras...Tokenizer() 'OOV'의 인덱스를 1로 처리

* <font size=4 color =red><b> 문장집합 --> 문장/단어 토큰화 --> 사전 --> 임베딩(원래대로) --> 패딩(문장길이맞추기)

# <b>[88] 단어 빈도수

In [39]:
from collections import Counter
word_list = ['barber', 'person', 'barber', 'good', 'person', 'barber', 'huge', 'person', 'knew', 'secret', 'secret', 'kept', 'huge', 'secret', 'huge', 'secret', 'barber', 'kept', 'word', 'barber', 'kept', 'word', 'barber', 'kept', 'secret', 'keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy', 'barber', 'went', 'huge', 'mountain']

vocab = Counter(word_list) #--단어리스트
print(vocab)               #--정렬 딕셔너리
print(vocab['barber'])

Counter({'barber': 8, 'secret': 6, 'huge': 5, 'kept': 4, 'person': 3, 'word': 2, 'keeping': 2, 'good': 1, 'knew': 1, 'driving': 1, 'crazy': 1, 'went': 1, 'mountain': 1})
8


* <font color ='red' size = 4><b> dict Top-N

In [40]:
vocab.most_common(5)

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3)]

# <b>[99] dict 정렬

In [37]:
vocab =  {'barber': 8, 'person': 3, 'good': 1, 'huge': 5, 'knew': 1, 'secret': 6, 'kept': 4}
vocab

{'barber': 8,
 'person': 3,
 'good': 1,
 'huge': 5,
 'knew': 1,
 'secret': 6,
 'kept': 4}

In [38]:
vocab_sorted = sorted(vocab.items(), key = lambda x:x[1], reverse = True)
print(vocab_sorted)

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3), ('good', 1), ('knew', 1)]


# 신조어 
* #pip install soynlp